### ISSUE TITLE
Video doesn't auto play, but there is still pause button instead of play button

### ISSUE THREAD

**Issue by wkuranowski** [kurtextrem/StopAutoplay#3] opened 2015-07-13 15:13 UTC
Hello.

I am using non-extended version of your extension. Extension works great, but I often (not always) see an annoying issue. When I want to play auto-paused youtube video I see that pause button is still there, but there should be a play button. It's annoying because in that case I need to click twice to start video. There is no such problem in other extensions like "Turn Off The Lights", where auto-pause feature works great, but I prefer to use your nice and simple extension.

**Comment by kurtextrem** [comment] 2015-07-13 15:39
Thank you for the report, but I can't reproduce. Can you take a screenshot? Also, it could be that some extensions are conflicting.
Could you please go to http://youtube.com/testtube and activate that player. Can you report back, whether it is working correctly there or not?

Thank you :)

**Comment by wkuranowski** [comment] 2015-07-13 17:06
Activating a new youtube player and disabling all extensions didn't help. I don't think that screenshot will tell you anything - it's just pause button instead of play button :)

Please try to open 30 tabs with a random youtube movie and look for a pause button. In my case it's about 10 tabs with that button

**Comment by kurtextrem** [comment] 2015-07-15 11:39
I think I reproduced the issue now. Need to find out why and how to fix it.

**Comment by kurtextrem** [comment] 2015-07-15 13:35
I did a major overhaul of the code, I'm not sure if this issue is fixed with that (but I think it should). I'll test and publish it this week.

**Comment by kurtextrem** [comment] 2015-07-15 13:54
By the way, what would you expect? (the non extended version
a) It auto stops everything
b) It doesn't auto stop when you have the tab focused (for example: You have one video open, click on one of the suggestions. Should that suggested video now auto play or not?)

**Comment by wkuranowski** [comment] 2015-07-15 14:05
As for me - "b", it's how it works now.

I think that the best solution is to have only one extension with configuration.

**Comment by kurtextrem** [comment] 2015-07-19 12:01
My laptop's fans are broken right now and they're getting repaired. Will
delay the update...

About config: Of course I thought about that, but I want to have my
extension as slim as possible. The form I use to achieve this doesn't have
access to the storage where an options page would store the options.
It would need an extra background script, and that doesn't fit my "slim"
idea.

2015-07-15 16:05 GMT+02:00 wkuranowski <notifications@github.com>:

**Comment by kurtextrem** [comment] 2015-07-30 08:29
I'm in the final testing phase for 2.0 now, every bug I could think if of is gone. Let's see if there is nothing left.
If everything works I'll release in a few days.

**Comment by kurtextrem** [comment] 2015-08-02 20:53
Published the version now. Once 2.0 landed on your pc, give me feedback! :)

**Comment by wkuranowski** [comment] 2015-08-11 12:44
Everything looks good now. Thanks!

**Comment by kurtextrem** [comment] 2015-08-11 13:09
Good! By the way: Do you also have the issue, that sometimes the whole youtube pages doesn't finish loading (= thumbnails aren't shown and it doesn't stop autoplay)?
I'm not sure if it is because of my / another extension, or if it's a chrome dev channel / youtube issue.

**Closed by kurtextrem** 2015-08-11 13:09 UTC
Labels: bug

**Comment by wkuranowski** [comment] 2015-08-11 14:48
I don't have that issue...
